base_model: "Qwen/Qwen3-0.6B-Base" # "openai-community/gpt2" 
dataset_name: "argilla/ultrafeedback-binarized-preferences-cleaned"
limit: 5000
max_length: 1024
batch_size: 2
lr: 5e-5
epochs: 1
warmup_ratio: 0.1
grad_accum_steps: 16
max_grad_norm: 1.0
evaluate_on_reward_bench: tru
reward_bench_subset: "Precise IF"
use_wandb: true
wandb_project: "pref_rm"
wandb_run_name: null
wandb_mode: "online"
log_every: 1
